name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Fix v1 embedding forever
        run: |
          rm -rf android
          flutter create . --platforms=android --org com.metamoot --project-name metamoot_pro_al
          flutter pub get
      - name: Build APK
        run: flutter build apk --debug
      - uses: actions/upload-artifact@v4
        with:
          name: metamoot-pro-apk
          path: build/app/outputs/flutter-apk/app-debug.apk